server:
  port: 7782
  servlet:
    context-path: /api
spring:
  docker:
    compose:
      enabled: false
      # file: ./api/src/main/resources/docker-compose.yml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    jakarta:
      persistence:
        schema-generation:
          database:
            action: none
          scripts:
            action: none
            create-source: metadata
            create-target: ./api/src/main/resources/db/script/schema.sql
  datasource:
    url: jdbc:postgresql://localhost:5434/idp
    password: 123456
    username: idp_dev
    schema: api
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: '20000'
      idle-timeout: '10000'
      maximum-pool-size: '40'
      auto-commit: 'true'
      minimum-idle: '10'
  liquibase:
    url: jdbc:postgresql://localhost:5434/idp
    password: 123456
    user: idp_dev
    schema: api
    enabled: true
    change-log: classpath:db/changelog-master.yml
    #    change-log: classpath:db_version/changelog-master.yml
    parameters:
      sql_user_name_1: user1
      sql_user_name_2: user2
      sql_user_name_3: user3
      sql_user_name_4: user4

logging:
  level:
    liquibase: DEBUG
    org:
      hibernate: DEBUG
      springframework:
        security: TRACE
        data: DEBUG

springdoc:
  swagger-ui:
    csrf:
      enabled: true
  api-docs:
    path: /api-docs

jwt:
  secret: RXN0aGVyemluaGFBbW9yRGFNaW5oYVZpZGE=
  expiration_ms: 86000000
  auth:
    converter:
      resource-id: idp
      principal-attribute: principal_username

keycloak:
  url: http://keycloak_local/realms/brazona
  name: idp
  grant: password
  client:
    id: idp
    secret: mwbc1c6qJL2ifrBdqA5X26cDpxEoDSsS